"""initial schema

Revision ID: 60ea3f66d449
Revises:
Create Date: 2026-06-20 11:44:02.317087

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60ea3f66d449"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "companies",
        "total_funding_usd",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_jobs_fts_gin"),
        table_name="jobs",
        postgresql_using="gin",
        postgresql_where="(is_active = true)",
    )
    op.create_index(
        "ix_jobs_fts_gin",
        "jobs",
        [
            sa.literal_column(
                "to_tsvector('english', coalesce(title,'') || ' ' || coalesce(description_snippet,'') || ' ' || coalesce(role_category,''))"
            )
        ],
        unique=False,
        postgresql_using="gin",
        postgresql_where=sa.text("is_active = TRUE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_jobs_fts_gin",
        table_name="jobs",
        postgresql_using="gin",
        postgresql_where=sa.text("is_active = TRUE"),
    )
    op.create_index(
        op.f("ix_jobs_fts_gin"),
        "jobs",
        [
            sa.literal_column(
                "to_tsvector('english'::regconfig, (((COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(description_snippet, ''::character varying)::text) || ' '::text) || COALESCE(role_category, ''::character varying)::text)"
            )
        ],
        unique=False,
        postgresql_using="gin",
        postgresql_where="(is_active = true)",
    )
    op.alter_column(
        "companies",
        "total_funding_usd",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
